### PR TITLE
Compatibility with PyProj v2.6.0

### PR DESCRIPTION
**Pull request by avalentino**
- [ ] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff``

### CODE REVIEW

**Comment by avalentino** [comment]
OK, the problem on OSX seems to be not related to this PR.
Also on my branch all seems to work correctly [1].

[1] https://travis-ci.org/github/avalentino/pyresample/builds/664359903

**Comment by mraspaud** [comment]
@djhoese do we have an issue for this ?

**Comment by avalentino** [comment]
@mraspaud , in case you are interested in, there is a debian bug for this.
It has been discovered after the update of pyproj in the debian archive.

**Comment by mraspaud** [comment]
@avalentino thanks! I was thinking about having an issue regarding the usage of cython exports directly, sorry for being unclear.

**Comment by djhoese** [comment]
No I don't think there is. It was one of those things that since it isn't broken I wasn't going to worry about fixing it since it would be a lot of research and time potentially.

**Comment by mraspaud** [comment]
Ok, merging this. @avalentino thank you for the quick PR!

**Comment by djhoese** [comment]
So I know this is merged but I looked up what options there are from loading from the cython module directly. It looks like this could be replaced with `from pyproj._proj cimport _Proj` (note the `cimport`). However, given the small things I have customized in ll2cr with how I use `Proj`, this refactor should wait until we have a hard requirement on a newer Pyproj. Newer versions of Pyproj (I think) keep lat/lon degrees as degrees and it wouldn't copy arrays which is exactly what I wanted.

**Pull request merged**
