### PR TITLE
[WIP] Compatibility with PyProj >= 3.0

### PR DESCRIPTION
**Pull request by avalentino**
This PR  should fix compatibility with PyProj >= 3.0.
Probably the implementation is not as fast as in the case of PyProj < 3.0 but at least it does not raise errors.

The PR also include the re-generated C file for ``_ll2cr.pyx``. Not sure if there is some specific constraint on the Cython version to be used. 

 - [ ] Tests added
 - [ ] Tests passed
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff``

### CODE REVIEW

**Comment by avalentino** [comment]
Not sure if the error in RTD is due to changes in this PR. Can you please provide some guidance?

**Comment by djhoese** [comment]
I have another PR open which fixes the RTD problem. Pyproj 3 requires using a newer pip than I was accidentally using with RTD.

**Comment by djhoese** [comment]
Actually your changes should all be included in my PR #310

**Comment by avalentino** [comment]
> Actually your changes should all be included in my PR #310

Indeed, I see it now.
Sorry I haven't looked at already open PRs before opening this one.
Closing.

**Pull request closed without merging**
