### PR TITLE
Remove `__file__` usage in test units for `test_files` path

### PR DESCRIPTION
**Pull request by ghiggi**
- [ ] Closes #xxxx 
 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented 

Remove `__file__` usage in test units for `test_files` path.

### CODE REVIEW

**Comment by ghiggi** [comment]
@mraspaud @djhoese ready for review. 
Let me know if you prefer to have `test_files_path` lower case or upper case, and if to be located in `test/conftest` or `test/utils`

**Review by mraspaud — APPROVED** [review]
LGTM!

**Comment by djhoese** [comment]
My one comment which is the same as in the other PR is that I think should should have been a Path object. `Path(__file__).resolve().parent()`. Otherwise, good enough.

**Comment by mraspaud** [comment]
Sorry, I merged too fast

**Pull request merged**
