### PR TITLE
Add missing test data to package

### PR DESCRIPTION
**Pull request by avalentino**
Install test data to be able to run the test suite also when the package is installed.

 - [ ] Tests added
 - [x] Tests passed
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff``
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
I could be wrong, but I think something has to be added to the MANIFEST.in file too. Could you double check that the files are included in the sdist?

**Comment by avalentino** [comment]
> I could be wrong, but I think something has to be added to the MANIFEST.in file too. Could you double check that the files are included in the sdist?

@djhoese yes test files are included in the sdist.
If you want I can add it to the manifest anyway.

**Comment by djhoese** [comment]
Yeah that'd be appreciated. Thanks.

**Comment by avalentino** [comment]
@djhoese done

**Comment by pnuu** [comment]
I made some fixes to Azure, Appveyor and Travis builds in #303, which is now merged, so merging `master` to your PR branch should help with the tests.

**Comment by avalentino** [comment]
Thanks @pnuu , I have just rebase the branch

**Pull request merged**
