### PR TITLE
Pre master

### PR DESCRIPTION
**Pull request by meteoswiss-mdr**
Ciao Martin,

here are two new functions inside the geometry.py file.
get_area_extent_for_subset   retrieves the area extend in meter (input are the xy indices)
get_xy_from_proj_coords       retrieves the xy indices, when proj coordinates in meter are given 

Cheers,
Ulrich

### CODE REVIEW

**Comment by mraspaud** [comment]
@meteoswiss-mdr you seem to have added a pyc file to the pr, could remove and prune ?

**Comment by davidh-ssec** [comment]
@mraspaud Which file exactly? I don't see one. It looks like one of the commits includes removing a pyc file.

**Comment by mraspaud** [comment]
@davidh-ssec yes, but it should be pruned not to add unnecessary blobs to the repo

**Comment by davidh-ssec** [comment]
Ah Gotcha

**Comment by mraspaud** [comment]
@meteoswiss-mdr ok, we'll do a squash and merge, it's simpler

**Pull request merged**
