### PR TITLE
Fix resolution computation for SwathDefinition.aggregate

### PR DESCRIPTION
**Pull request by loerum**
Fix calculation of new resolution in SwathDefinition.aggregate.

### CODE REVIEW

**Comment by loerum** [comment]
I will look for unit test

**Comment by loerum** [comment]
I have added a test of the resolution attribute.

**Comment by loerum** [comment]
@djhoese I can not reproduce the assert exception in my container (ubuntu 18.04, python3.6), do you know how many warnings is generated in test_custom ?

**Comment by djhoese** [comment]
I'm fixing this in #236. Once that is merged we can merge this. I'll re-review the test failures for this PR and verify that your changes aren't breaking anything.

**Comment by loerum** [comment]
Thanks !

**Comment by djhoese** [comment]
Thanks again for this. The tests are now fixed on the master branch so I'm merging this. Thanks!

**Pull request merged**
