### PR TITLE
Switch to cibuildwheel for wheel building

### PR DESCRIPTION
**Pull request by djhoese**
Join the modern world and use cibuildwheel to build wheels.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
@mraspaud Ah we need Python 3.12 wheels for pykdtree. I guess I'll do the equivalent of this PR there.

**Comment by mraspaud** [comment]
thanks!

**Comment by djhoese** [comment]
The CI failures will be fixed when PROJ 9.3.1 is released:

https://github.com/OSGeo/PROJ/pull/3873

9.3.0 still triggers the inequality.

**Comment by djhoese** [comment]
FYI @mraspaud, feel free to review and merge this. This does *NOT* enable Python 3.12 because shapely does not have wheels for it you (I'm working on that in https://github.com/shapely/shapely/pull/1893) and I also excluded the specific version of PROJ that causes our one .cfg -> YAML area definition test to fail until PROJ 9.3.1 is released.

Once the shapely PR is merged and a wheel released we can do a release. I'd love for all of pytroll's packages to have Python 3.12 wheels available on PyPI when 3.12's first stable release comes out.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Pull request merged**
