### PR TITLE
Fix example data for BIL, clarify text and add missing output_shape p…

### PR DESCRIPTION
**Pull request by pnuu**
This PR fixes too sparse data in documentation examples for bilinear interpolation, and also clarifies the text and adds an unlisted `output_shape` parameter in `bilinear.get_sample_from_bil_info()`.

### CODE REVIEW

**Comment by pnuu** [comment]
#72

**Comment by davidh-ssec** [comment]
@pnuu Would you mind rebasing this PR on the current develop since it includes changes that should fix the failing travis tests on this PR.

**Comment by pnuu** [comment]
Rebased to current develop.

**Comment by davidh-ssec** [comment]
Hit memory limit on this one, but it's fine.

**Pull request merged**
