### PR TITLE
Check area slices for correct step

### PR DESCRIPTION
**Pull request by pnuu**
This PR makes sure that the `slice(start, stop, step)` has correct sign for the `step` argument when `start > stop` when slicing the area.

 - [x] Closes https://github.com/pytroll/pyresample/issues/274 https://github.com/pytroll/satpy/issues/930 
 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff``

### CODE REVIEW

**Comment by gerritholl** [comment]
I still get a segfault when trying to use this with https://github.com/pytroll/satpy/pull/1188 when loading the area definition from the yaml file, but not when defining it inline.  I'm trying to figure out what's going on.

**Comment by gerritholl** [comment]
My previous comment was a lie.  It does also fail when defining it inline; I still had the `reduce_data=False` flag active.

Specifically, this still segfaults:

```python
from satpy import Scene
from satpy.utils import debug_on
from pyresample import create_area_def
debug_on()
from glob import glob
area = create_area_def("fci_0deg_2km",
        {"proj": "geos", "lon_0": 0, "h": 35786400, "x_0": 0, "y_0": 0, "ellps": "WGS84"},
        units="m",
        shape=(5568, 5568),
        area_extent=(-5567999.994206558, -5567999.994200589,
            5567999.994206558, 5567999.994200589))
sc = Scene(glob("/media/nas/x21308/2020_04_MTG_unofficial_Testdata/20130804_RC72/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY--L2P-NC4E_C_EU*.nc"), reader="fci_l1c_fdhsi")                                                                                                                           
sc.load(["ir_123"])
nsc = sc.resample(area)
nsc.save_dataset("ir_123", "/tmp/ir_123.tif")
```

Meanwhile, this completes successfully (previously `AssertionError`):

```python
from satpy import Scene
from satpy.utils import debug_on
from pyresample import create_area_def
debug_on()
from glob import glob
area = create_area_def("fci_0deg_2km",
        {"proj": "geos", "lon_0": 0, "h": 35786400, "x_0": 0, "y_0": 0, "ellps": "WGS84"},
        units="m",
        shape=(5568//10, 5568//10),
        area_extent=(-5567999.994206558/10, -5567999.994200589/10,
            5567999.994206558/10, 5567999.994200589/10))
sc = Scene(glob("/media/nas/x21308/2020_04_MTG_unofficial_Testdata/20130804_RC72/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY--L2P-NC4E_C_EU*.nc"), reader="fci_l1c_fdhsi")                                                                                                                           
sc.load(["ir_123"])
nsc = sc.resample(area)
nsc.save_dataset("ir_123", "/tmp/ir_123.tif")
```

ir_123

**Comment by gerritholl** [comment]
After the segmentation fault, the last line in `dmesg` is:

```
[9527227.302060] python[13518]: segfault at 564456e99e40 ip 00007fcaba50b033 sp 00007fcaa6ffc098 error 4 in kdtree.cpython-38-x86_64-linux-gnu.so[7fcaba4fa000+13000]
```

**Comment by pnuu** [comment]
Added explanation, and merging.

**Pull request merged**
