### PR TITLE
Fix bil mask deprecation

### PR DESCRIPTION
**Pull request by pnuu**
This PR fixes how the invalid coordinates were handled in bilinear interpolation, indicated by deprecation warning raised by Numpy. If there's a better way of doing this (compare to the original version), I'm happy to update the PR.

Also UserWarning about possible extra neighbours inside search radius is now suppressed, as the number of retrieved neighbours is more or less static.

### CODE REVIEW

**Comment by davidh-ssec** [comment]
So is the catch warnings supposed to catch a UserWarning or the warning from numpy when handling invalid coordinates and assigning NaN?

**Comment by pnuu** [comment]
I should only catch the UserWarning, but now that look at it it might catch everything. I need to look more what happens.

**Comment by pnuu** [comment]
After some testing, the only warning raised is the UserWarning about more than N neighbors within the search radius. This is unrelated to #72.

**Comment by davidh-ssec** [comment]
So @pnuu is this ready to be merged then?

**Comment by pnuu** [comment]
Yes, ready for merging.

**Pull request merged**
