### PR TITLE
Create AreaDefinition from epsg codes

### PR DESCRIPTION
**Pull request by mraspaud**
This PR adds the possibility to create AreaDefintions from EPSG codes that include an area of use.

 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [x] Fully documented 

The usage is for example:
`sweref = AreaDefinition.from_epsg('3006', 1000)`
to get the SWEREF99 TM area in 1km resolution.

Some example of imagery generated with satpy for epsg 3006 and 3034:

### CODE REVIEW

**Comment by mraspaud** [comment]
I realise now this is not perfect, as bounds defined in the epsg is different from the corner pixels. Further enhancements will be taken in a future PR I think.

**Comment by pnuu** [comment]
> I realise now this is not perfect, as bounds defined in the epsg is different from the corner pixels. 
What do you mean? At least `EPSG:4326` has the outer corners as the bounds.

But what I've noticed, is that the bounds given for different EPGS codes depend on the source. For example https://epsg.io/3035 has lon/lat bounds `-16.1, 32.88, 40.18, 84.17` and https://spatialreference.org/ref/epsg/etrs89-etrs-laea/ has `-10.6700, 34.5000, 31.5500, 71.0500`. I've used the latter in my own area definitions.

**Comment by mraspaud** [comment]
@pnuu: see here also: https://github.com/pyproj4/pyproj/issues/627
Apparently http://www.epsg-registry.org/ is the most up to date.

**Comment by pnuu** [comment]
Oh, interesting. I wonder how the extents could be wrong in epsg.io, these should be rather established stuff. But good to know the official source. Anyway, the bounds in EPSG are for the outer edges, right?

**Comment by mraspaud** [comment]
It seems epsg.io can be outdated. Yes, it's the outer edges from what I understand as they call it bounding box.

**Pull request merged**
