### PR TITLE
Change create_areas_def to dump and set default yaml style

### LINKED ISSUE #152: Add dump/dumps methods to AreaDefinition
There is currently a `create_areas_def` method in `AreaDefinition` that produces the YAML needed to save the area to a file. I was thinking we could change this to `dump` and/or `dumps` similar to `json` (and maybe other libraries). `dumps` would return a string and `dump` would take a file-like object and write this string to a file. I could see how the `dump` is method is not needed or could be fulfilled by a keyword argument to `dumps`...in which case maybe it should just be `dump`?

### PR DESCRIPTION
**Pull request by BENR0**
- [x] Closes #152 and #307 
 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Review by djhoese — COMMENTED** [review]
Nice idea. I feel like `dump` was brought up in the past as an option and may have had some people who didn't like it. Maybe @mraspaud remembers. I like the idea.

Do you think you could add some simple tests for writing to a file?

**Comment by pnuu** [comment]
Merging the current `master` branch should fix at least Azure and Appveyor builds, most likely also Travis builds.

**Comment by pnuu** [comment]
The DeepCode and Stickler warnings seem to be easily fixed, but at least the other builds now pass.

**Comment by djhoese** [comment]
@BENR0 would you mind looking at the stickler complaints?

**Comment by BENR0** [comment]
Apparently I already fixed the complaints just didn't push them. Sorry about that.

**Comment by mraspaud** [comment]
Thanks, merging

**Pull request merged**
