### PR TITLE
Set summed bin without data to fill_value

### LINKED ISSUE #354: `get_sum` not matched with `bucket_sum`
#### Code

```python
import proplot as plot
import pyresample
import xarray as xr
from satpy import Scene
from pyresample import create_area_def
from pyresample.bucket import BucketResampler

abi_dir = '../data/GOES-16/ABI_L2/'
channel = 'HT'
reader = 'abi_l2_nc'

lon_min = -125
lon_max = -65
lat_min = 25
lat_max = 50
resample_res = 0.2 # resolution of resample grid (units: degree)

area = create_area_def('track_area',
                       {'proj': 'longlat', 'datum': 'WGS84'},
                       area_extent=[lon_min-resample_res/2,
                                    lat_min-resample_res/2,
                                    lon_max+resample_res/2,
                                    lat_max+resample_res/2],
                       resolution=resample_res,
                       units='degrees',
                       description=f'{resample_res}x{resample_res} degree lat-lon grid')

scn = Scene(['../data/GOES-16/ABI_L2/OR_ABI-L2-ACHAC-M6_G16_s20201530001131_e20201530003504_c20201530006018.nc'],
            reader=reader)
scn.load([channel])
new_scn = scn.resample(area, cache_dir=cache_dir, resample='bucket_sum')

lons, lats = scn[channel].area.get_lonlats()
resampler = BucketResampler(area,
                            xr.DataArray(lons).chunk(chunks={'dim_0':100}).data,
                            xr.DataArray(lats).chunk(chunks={'dim_0':100}).data)
sums = resampler.get_sum(scn[channel])

new_lons, new_lats = new_scn[channel].area.get_lonlats()
fig, axs = plot.subplots(axwidth=6, ncols=3, share=0)

scn[channel].plot(ax=axs[0], cmap='viridis')

m1 = axs[1].pcolormesh(new_lons, new_lats, new_scn[channel], cmap='viridis')
axs[1].colorbar(m1, loc='r')

m2 = axs[2].pcolormesh(new_lons, new_lats, sums, cmap='viridis')
axs[2].colorbar(m2, loc='r')

axs.format(collabels=['Original CTH', 'bucket_sum', 'Manual summation'])

fig.savefig('comparison.jpg')
```
#### Problem description

1. Abnormal strips of the `get_sum` plot
2. Missing data in the lower-left corner of the `bucket_sum` plot
3. `get_sum` not matched with `bucket_sum`

#### Actual Result, Traceback if applicable

comparison

#### Versions of Python, package at hand and relevant dependencies
```
satpy 0.27.0
pyresample 1.19.0
```

### PR DESCRIPTION
**Pull request by zxdawn**
The `get_sum()` function doesn't accept the `fill_value` kwarg and will raise error. We can set it as kwrgs with the `np.nan` default value.

So, if there's no input of `fill_value`, summation will be 0 for bins without data. If the `fill_value` exists, then set it to `fill_value`.

 - [ ] Closes #354
 - [ ] Tests added 
 - [ ] Tests passed 
 - [x] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
@zxdawn or @pnuu is this still useful or needed? It looks like we missed reviewing this and I have typically stayed away from bucket resampler changes as I don't understand most of it.

**Comment by zxdawn** [comment]
I suppose so. Because `get_min`, `get_max`, `get_average`, and `get_fractions` all have this option.

**Comment by mraspaud** [comment]
@pnuu could you have a look here?

**Comment by pnuu** [comment]
Will do after my current endeavor with reader warnings.

**Review by pnuu — CHANGES_REQUESTED** [review]
In general looks good, just needs the conflicts to be resolved and a test case.

**Comment by pnuu** [comment]
Oh no, the code has changed so much that resolving the conflicts will take some time :see_no_evil:

**Comment by pnuu** [comment]
At least the existing tests now pass (locally).

**Review by mraspaud — COMMENTED** [review]
Should there be a test for this?

**Comment by pnuu** [comment]
Yes, there should. @zxdawn do you have time to add something? I might have some time on monday, just need to remember...

**Comment by mraspaud** [comment]
I'll turn this into a draft for now then.

**Comment by zxdawn** [comment]
Maybe I have some time on Sunday or Tuesday.

**Comment by djhoese** [comment]
Implemented in a different way in #602. Closing...

**Pull request closed without merging**
