### PR TITLE
Drop Python 3.8 support

### PR DESCRIPTION
**Pull request by djhoese**
It's what all the cool kids are doing.

### CODE REVIEW

**Comment by djhoese** [comment]
Note I also removed some old multiprocessing import code in setup.py that said it could be removed when Python 2 support was dropped.

**Review by pnuu — APPROVED** [review]
LGTM

**Comment by pnuu** [comment]
Gnaah. Don't know what I did there. But LGTM.

One thought I had was that maybe the `python_requires` shouldn't be so strict, most of the code will work fine with earlier versions. Though even in that case we should state that only the tested Python versions are actually supported.

**Comment by djhoese** [comment]
I'm noticing codecov is complaining of lost coverage in the multiprocessing parts (`_spatial_mp.py`) for modules that haven't been changed, even in #498 which doesn't have these python version changes. Makes me wonder if something has changed in some package (numpy? pyproj?) that is no longer accessing the `__iter__` or other parts of these modules.

**Comment by djhoese** [comment]
> Though even in that case we should state that only the tested Python versions are actually supported.

The problem is that `python_requires` can control what versions of the library PyPI returns. So if we make a release that supports Python 3.7 and then make a bug fix release that introduces syntax that is 3.8+ only then we'd have to remember to drop support in a bug fix version (or release a new minor release just for a bug fix). My point is I think CI needs to stay in sync with what we advertise as supported and it might be better to do it sooner rather than later. :man_shrugging:

**Comment by pnuu** [comment]
Ah, right. That'd get complicated and confusing quickly. So yeah, lets stay in sync with the CI.

**Pull request merged**
