### PR TITLE
Add a GCPDefinition class

### PR DESCRIPTION
**Pull request by mraspaud**
This PR adds a gcps attribute to the SwathDefinition class

 - [x] Tests added 
 - [ ] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
What is the functional difference between this and splitting the points in to separate lons/lats arrays?

**Comment by mraspaud** [comment]
This allows GCPs to be in a variety of already existing formats, for example rasterio and gdal gcps that comprise not only lon and lat, but also corresponding x, y, and altitude sometimes.

**Comment by djhoese** [comment]
Is adding this to SwathDefinition the best way? Would a subclass be more flexible/useful? Can't GCPs technically be used for gridded data (not a swath)?

**Comment by mraspaud** [comment]
Well, I've been pondering about a subclass, but I think the changes to SwathDefinition are minimal, hence reusing SwathDefinition. As for gridded data, I haven't seen GCPs used in such a case, so I don't know.

An alternative I could add this functionality to a mixin class.

**Comment by mraspaud** [comment]
Not really relevant anymore, closing.

**Pull request closed without merging**
