### PR TITLE
Add pre-commit running to PRs and add isort

### PR DESCRIPTION
**Pull request by djhoese**
`isort` consistently sorts imports between third-party imports, first-part imports, and standard library imports.

This PR turns that on in the pre-commit config but also is the first PR to have the pre-commit.ci service turned on for pyresample. I've configured it in this PR to not autofix the PR.

Let's see how this goes and how much @mraspaud hates it.

### CODE REVIEW

**Comment by djhoese** [comment]
So I made an issue on the pre-commit.ci bug tracker. It is against their philosophy to only run pre-commit on the PRs changes (incrementally as it were) as it results in contributors getting stuck with huge pre-commit issues for unrelated changes. The maintainer of pre-commit.ci recommends running pre-commit on the entire repository.

**Comment by djhoese** [comment]
Well looks like I'm going to be fixing the entire pyresample package's style issues...

I'll work on it more tomorrow.

**Comment by djhoese** [comment]
This PR:

- [x] fixes *all* flake8 (docstring, bugbear, etc).
- [x] Adds a CI job for building the website and not allowing any warnings (catch docstring issues early)
- [x] Adds isort pre-commit job
- [x] Runs pre-commit against the entire project

**Review by mraspaud — APPROVED** [review]
Thanks a lot for taking the time to fix all the flake8 issues! Nice that the files are not fixed automatically but manually instead. LGTM!

**Pull request merged**
