### PR TITLE
Add `get_min` and `get_max` to Bucket resampler (experimental)

### PR DESCRIPTION
**Pull request by zxdawn**
This PR adds two functions to Bucket: `get_min` and `get_max`.

 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by zxdawn** [comment]
Example of processing ABI L2 CTH data:


image

**Comment by djhoese** [comment]
You mentioned on slack that there is code repeated between the two methods. Would it be possible to make a generic method that is given the function name to pass to scipy?

**Comment by djhoese** [comment]
Also how does this perform for some of the other functions provided by `binned_statistics` that are already implemented here (mean/average, count, sum, etc)? Would it be better to copy from the existing functions to support min/max if it means better performance? Or should those be switched to depend on scipy?

**Comment by zxdawn** [comment]
As discussed in slack, we prefer the xarray or dask method.
1. xarray method
    `range()` isn't supported in xarray's `groupby_bins` function (see [this issue](https://github.com/pydata/xarray/issues/5358)).
2. dask method
    dask only supports part of scipy.stats (see the [Doc](https://docs.dask.org/en/latest/array-stats.html)). `binned_statistics` isn't in the list.

**Comment by zxdawn** [comment]
@djhoese I switched to the xarray method. The `weights` needs to be DataArray and I set it to DataArray by `xr.DataArray()`. The speed of calculation is quite low ... It should be something related with dask. Do you have any suggestions?

**Comment by djhoese** [comment]
I think overall the groupby operations by xarray don't perform well. There was a presentation at the dask summit this week about a dask-centric groupby package that is being worked on, but it is only experimental at this point. Otherwise I think a custom implementation would be needed. I don't know enough about how the bucket resampler works to give any more advice. Maybe @pnuu ?

**Comment by zxdawn** [comment]
@djhoese Yes, the xarray groupby operations are too slow. So, instead I tested the pandas method.

# Test
## Method1: pandas groupby with pd.cut
```
length = int(1e5)
x = np.arange(length)
df = pd.DataFrame({'values': x*5})
groups = df.groupby(pd.cut(x, bins=np.linspace(0, length, length+1), right=False, include_lowest=True))
bin_min = groups['values'].min()
```
2.31 s ± 4.51 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

## Method2: pandas groupby with np.digitize
```
%%timeit

length = int(1e5)
x = np.arange(length)
df = pd.DataFrame({'values': x*5})
groups = df.groupby(np.digitize(x, bins=np.linspace(0, length, length+1)))
bin_min = groups['values'].min()
```
6.65 ms ± 4.33 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

##  Method3: dask pandas groupby with np.digitize
```
%%timeit

length = int(1e5)
df = pd.DataFrame({'x': np.arange(length), 
                   'values': np.arange(length)*5})

df_dask = dd.from_pandas(df, npartitions=3)

bin_min = df_dask.map_partitions(lambda part: part.groupby(np.digitize(part.x,
                                                                       bins=np.linspace(0, length, length+1)
                                                                      )
                                                          )['values'].min()).compute()
```
15.9 ms ± 772 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

##  Increasing the data length
The new result of consumed time is
```
method1: 24.1 s ± 101 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
method2: 108 ms ± 834 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
method3: 72.5 ms ± 7.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

If I change `npartitions` to 10, the speed is quicker:
```
method3: 59.3 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
If `npartitions` is set to 1, it's much slower:
```
212 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
## Summary
I think we can use dask pandas groupby with np.digitize. However, I don't know how to set the suitable npartitions automatically.

**Comment by zxdawn** [comment]
I create the dask DataFrame directly from dask array. It works well now.

**Comment by zxdawn** [comment]
The calculation speed is not quite good compared with other resampler method ...

```
$ blended_scene.resample(coarse_area, resampler='bucket_count')
25.3 ms ± 369 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

$ blended_scene.resample(coarse_area)
36.7 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

$ blended_scene.resample(coarse_area, resampler='bucket_min')
14.3 s ± 93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Any idea of how to speed up?

**Review by pnuu — APPROVED** [review]
LGTM, and thanks for adding the features!

As discussed on Slack, a short note on (current) slowness in the `get_min()` and `get_max()` docstrings would be nice.

**Comment by zxdawn** [comment]
The docstring is added, but the cross-linked function `_call_pandas_groupby_statistics` can't be clicked:
image

**Comment by djhoese** [comment]
This is likely because by default sphinx won't document private (`_`) methods. I think you should just link to the pandas method directly. You'll likely need to add reference to pandas in the intersphinx mapping in `doc/conf.py`.

**Review by djhoese — APPROVED** [review]
Looks good to me.

CC to @dcherian that this PR would really benefit from your dask groupby work. I saw your presentation at the dask summit and that's why the project is referenced in the docstring here as a better option for what @zxdawn is trying to do.

**Comment by dcherian** [comment]
Thanks. @zxdawn you could test out https://github.com/dcherian/dask_groupby and see if there are any bugs. I think work is starting soon on integrating it in to xarray

**Comment by zxdawn** [comment]
@dcherian Thanks. I will test a simple example and submit an issue if there's any bug.

**Pull request merged**
