### PR TITLE
Switch docstrings to Google style

### PR DESCRIPTION
**Pull request by arpm**
- [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Wow, thanks for starting this. I'm guessing you're working for your hacktoberfest PRs?

It seems like you fixed the punctuation for some of the docstrings, but didn't change the numpy-style docstrings like those using:

```
Parameters
---------------
```

to Google style which uses `Args:` instead (among other changes). Additionally it is preferred that the first line in a docstring be a single sentence on one line. I noticed in some of the docstrings that you added a period but didn't re-write the docstring so it fit nicely on one line.

If you are still working on this let me know and I'll wait until you comment to let me know you are done before I continue reviewing the code.

Lastly, do you think you could try building the sphinx docs to make sure all these docstrings build properly (cd docs; make clean; make html; and then look for warnings/errors)?

Thanks again for working on this.

For our own github reference here is the related issue: #146

**Comment by arpm** [comment]
> Wow, thanks for starting this. I'm guessing you're working for your hacktoberfest PRs?
> 
> It seems like you fixed the punctuation for some of the docstrings, but didn't change the numpy-style docstrings like those using:
> 
> ```
> Parameters
> ---------------
> ```
> 
> to Google style which uses `Args:` instead (among other changes). Additionally it is preferred that the first line in a docstring be a single sentence on one line. I noticed in some of the docstrings that you added a period but didn't re-write the docstring so it fit nicely on one line.
> 
> If you are still working on this let me know and I'll wait until you comment to let me know you are done before I continue reviewing the code.
> 
> Lastly, do you think you could try building the sphinx docs to make sure all these docstrings build properly (cd docs; make clean; make html; and then look for warnings/errors)?
> 
> Thanks again for working on this.
> 
> For our own github reference here is the related issue: #146

1. I started replacing the dashes for a colon and 4 spaces of indentation. However, I am not in any way rewording the docstrings, for now.
2. Do you want all docstrings to be one liners or for me to write a one liner for each docstring?
3. I would like to keep on working (I am in fact looking to complete those sweet PRs for that sweet swag)
4. Could you elaborate on the last point (sphinx docs/docstring build)?

**Comment by djhoese** [comment]
1. I *think* the arguments have to be `nprocs (int): This is a description (optional).` Or some other way of describing it as optional. The `nprocs : int, optional` syntax is not standard google style docstrings iirc. Here's an old-ish example document: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2. All docstrings that exist for functions/methods/classes and look like this:

   ```python
   def a_func():
       """This is the docstring but it
       spans two lines and should be one line ending with a period.

       Other stuff can be down here.
       """
       # Code
   ```

   Should be updated so that "subject line" is one line and fits within 120 (preferably closer to 80) characters. This may require some rewording or simplification or splitting part of the sentence in to a second sentence that appears in the "body" of the docstring.

3. Nice.

4. We use the tool `sphinx` to generate our documentation site from the content in the `docs` directory. If you go in to that directory (and have sphinx installed) and run `make clean; make html` it will go through the process of converting restructuredtext documents to HTML. This includes parsing the pyresample source code's docstrings and generating API docs. If during this `make html` step it raises errors or warnings caused by the changes you make then it'd be good if you fixed them (there good be some that already exist that we missed). After generating the HTML you should be able to open the documentation by opening `docs/build/html/index.html` in your browser.

**Comment by arpm** [comment]
Does this look about right?

```
def resample_bilinear(data, source_geo_def, target_area_def, radius=50e3,
                      neighbours=32, nprocs=1, fill_value=0,
                      reduce_data=True, segments=None, epsilon=0):
    """Resample using bilinear interpolation.

    data (numpy array): Array of single channel data points or
        (source_geo_def.shape, k) array of k channels of datapoints
    source_geo_def (object): Geometry definition of source data
    target_area_def (object): Geometry definition of target area
    radius (float, optional): Cut-off distance in meters
    neighbours (int, optional): Number of neighbours to consider for each grid
        point when searching the closest corner points
    nprocs (int, optional): Number of processor cores to be used for
        getting neighbour info
    fill_value ({int, None}, optional): Set undetermined pixels to this value.
        If fill_value is None a masked array is returned with undetermined
        pixels masked
    reduce_data (bool, optional): Perform initial coarse reduction of source
        dataset in order to reduce execution time
    segments (int or None): Number of segments to use when resampling. If set
        to None an estimate will be calculated
    epsilon (float, optional): Allowed uncertainty in meters. Increasing
        uncertainty reduces execution time

    Returns:
        data (numpy array): Source data resampled to target geometry
    """

    # Calculate the resampling information
    t__, s__, input_idxs, idx_ref = get_bil_info(source_geo_def,
                                                 target_area_def,
                                                 radius=radius,
                                                 neighbours=neighbours,
                                                 nprocs=nprocs,
                                                 masked=False,
                                                 reduce_data=reduce_data,
                                                 segments=segments,
                                                 epsilon=epsilon)

    data = _check_data_shape(data, input_idxs)

    result = np.nan * np.zeros((target_area_def.size, data.shape[1]))
    for i in range(data.shape[1]):
        result[:, i] = get_sample_from_bil_info(data[:, i], t__, s__,
                                                input_idxs, idx_ref,
                                                output_shape=None)

    if fill_value is None:
        result = np.ma.masked_invalid(result)
    else:
        result[np.isnan(result)] = fill_value

    # Reshape to target area shape
    shp = target_area_def.shape
    result = result.reshape((shp[0], shp[1], data.shape[1]))
    # Remove extra dimensions
    result = np.squeeze(result)

    return result
```

**Comment by djhoese** [comment]
That looks pretty good. A couple things I'm not sure of:

1. I think there has to be an extra blank line at the end for some code/docstring linting tools. That way the "Returns:" block it followed by a "de-dent' back to the original indentation. Hope that makes sense.

2. I was going to argue that I didn't think `optional` went where you put it, but re-reading the doc I linked to it looks like you have it right.

3. Did you find an example that used the `{}` for the type declaration? I think I'd rather not have them.

4. There may be a better way of doing `numpy array` and I think @pnuu coded that specifically to handle numpy or dask arrays so it may be in-accurate to say that. I'd like @mraspaud and @pnuu 's opinion: should it say `ndarray`, `array-like`, `numpy array`, or something similar?

5. Maybe `BaseDefinition` or `AreaDefinition or SwathDefinition` could be used instead of `object` for the definition parameters? @pnuu @mraspaud?

**Comment by djhoese** [comment]
I'd want either the two Area/SwathDefinitions listed or something generic. Only listing AreaDefinition makes people think that only those are supported which, in my experience, is not what people have when they first resort to learning python so they can use pyresample.

**Comment by mraspaud** [comment]
4: `array-like`
5: `AreaDefinition or SwathDefinition`

**Pull request closed without merging**
